[tool.ruff]
line-length = 88
target-version = "py38"

[tool.ruff.lint]
# 1. Enable flake8-bugbear (`B`) rules, in addition to the defaults.
select = ["E4", "E7", "E9", "F", "B", "Q"]

# 2. Avoid enforcing line-length violations (`E501`)
ignore = ["E741", "E731"]


[tool.mypy]
disable_error_code = [
    "has-type",
    "misc",
    "union-attr",
    "var-annotated"
]
