[tool.ruff]
# line-length = 88
unsafe-fixes = true
exclude = ["builtins.pyi", "**/*.pyi"]

[tool.ruff.format]
skip-magic-trailing-comma = true

[tool.ruff.lint]
select = ["ALL"]

fixable = ["ALL"]
unfixable = []

# E731 - lambda assignment
# EXE002 - windows shares are all 777
# ERA001 - commented-out code
# PLR2004 - magic value comparison
# PLR0911 - too many return statements
# PLR0912 - too many branches
# PLR0913 - too many function parameters
# C901 - too complex
# ANN101 - missing type annotation for self
# ANN401 - ANY prohibited
# B023 - function definition does not bind loop variable
# COM812 - trailing comma missing
ignore = [
        "E731", "EXE002", "ERA001",
        "PLR2004", "PLR0911", "PLR0912", "PLR0913",
        "ANN101", "ANN401", "PGH003", "C901", "B023", "COM812"]

[tool.ruff.lint.per-file-ignores]
# S101 - assert detected.
# ANN201 - missing return type.
# D102 - missing docstring for public method.
"**/test_*" = ["S101", "ANN201", "D102"]

[tool.pylint."MESSAGES CONTROL"]

# Disable the message, report, category or checker with the given id(s).
disable="""
        unnecessary-lambda-assignment,
        too-few-public-methods,
        too-many-public-methods,
        too-many-arguments,
        too-many-statements,
        too-many-locals,
        too-many-lines
        """


[tool.pyright]
"reportOptionalMemberAccess" = false
"reportReturnType" = false
