[tool.ruff]
line-length = 88
target-version = "py38"

[tool.ruff.lint]
select = ["E", "F", "UP", "B", "Q", "SIM", "I"]

ignore = ["E741", "E731"]
exclude = ["builtins.pyi"]

[tool.mypy]
disable_error_code = [
    "has-type",
    "misc",
    "union-attr",
    "var-annotated",
    "annotation-unchecked",
    "func-returns-value",
    "operator",
    "arg-type"
]
